# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build:
    working_directory: ~/heterocl
    docker:
      - image: zzzdavid/llvm-project:15.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: large
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Build HCL-MLIR
          command: |
            export BUILD_DIR=/home/circleci/llvm-project/build
            export PREFIX=/home/circleci/llvm-project/build
            git clone https://github.com/cornell-zhang/hcl-dialect-prototype.git
            cd hcl-dialect-prototype
            mkdir -p build && cd build
            cmake -G "Unix Makefiles" .. \
                -DMLIR_DIR=$PREFIX/lib/cmake/mlir \
                -DLLVM_EXTERNAL_LIT=$BUILD_DIR/bin/llvm-lit \
                -DPYTHON_BINDING=ON \
                -DPython3_EXECUTABLE=`which python3`
            make -j4
            export PYTHONPATH=$(pwd)/tools/hcl/python_packages/hcl_core:${PYTHONPATH}
      - run:
          name: MLIR Tests
          command: |
            cd hcl-dialect-prototype/build
            cmake --build . --target check-hcl
      - run:
          name: Install HeteroCL Dependencies
          command: |
            python3 -m pip install -r python/requirements.txt
      - run: 
          name: HeteroCL Tests
          command: |
            export HCL_HOME=$(pwd)
            export LLVM_BUILD_DIR=/home/circleci/llvm-project/build
            export PYTHONPATH=$HCL_HOME/hcl-dialect-prototype/build/tools/hcl/python_packages/hcl_core:${PYTHONPATH}
            export PYTHONPATH=$HCL_HOME/python:$HCL_HOME/hlib/python:${PYTHONPATH}
            python3 -m pytest tests -v
      - run:
          name: HeteroCL Tutorials
          command: |
            export HCL_HOME=$(pwd)
            export LLVM_BUILD_DIR=/home/circleci/llvm-project/build
            export PYTHONPATH=$HCL_HOME/hcl-dialect-prototype/build/tools/hcl/python_packages/hcl_core:${PYTHONPATH}
            export PYTHONPATH=$HCL_HOME/python:$HCL_HOME/hlib/python:${PYTHONPATH}
            cd tutorials
            python3 -m pytest test_tutorial.py -v